"""update post table

Revision ID: a36adb15003e
Revises: 304e5fe052c1
Create Date: 2022-03-12 17:23:18.282441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36adb15003e'
down_revision = '304e5fe052c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_id')
    op.drop_column('posts', 'post_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
