"""add coments table

Revision ID: abccab63727a
Revises: 3425dda7b249
Create Date: 2022-03-13 10:43:06.776801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abccab63727a'
down_revision = '3425dda7b249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body', sa.String(), nullable=True))
    op.drop_column('posts', 'post_blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_blog', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'body')
    # ### end Alembic commands ###
